import type { Metadata } from "next";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import { Button } from "@mui/material";

export const metadata: Metadata = {
  title: "PhotoPhrase",
  description: "Generated by create next app",
};

const pages = ["Account", "Captions", "Settings"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <body>
          <AppBar position="fixed" color="inherit" style={{ height: "8rem" }}>
            <Toolbar style={{ justifyContent: "center", alignItems: "center" }}>
              {pages.map((page, index) => (
                <Button key={index}>{page}</Button>
              ))}
              <Typography variant="h6"></Typography>
            </Toolbar>
          </AppBar>
          <main> {children}</main>

          <footer></footer>
        </body>
      </html>
    </>
  );
}
